### ISSUE TITLE
提示严重错误

### ISSUE THREAD

**Issue by fenghongjian** [TBoyLi/FunIOS#1]
xcode提示：No such module 'MEVFloatingButton'
请教如何解决

**Comment by TBoyLi** [comment]
删除 pod  重新 pod 一下 试试 貌似没用到这个控件哦

**Comment by hanklee9820** [comment]
> xcode提示：No such module 'MEVFloatingButton' 请教如何解决

删除 pod 重新 pod 一下 试试 貌似没用到这个控件哦
